# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".

import json
from setuptools import setup

kwargs = json.loads(
    """
{
    "name": "valheim_commands",
    "packages": [
        "vh"
    ],
    "python_requires": ">=3.6",
    "version": "0.1.0"
}
"""
)

setup(**kwargs)
